### ISSUE TITLE
Updates to run_neon tutorial

### ISSUE THREAD

**Issue by danicalombardozzi** [NCAR/NEON-visualization#25]
A few things that we can improve in the tutorial:

1. running the 'run_neon' code block ends with a 'data not found' line and it isn't evident when it is finished running. Adding a print statement at the end that says 'simulation submitted to queue' or similar would be helpful.
2. when the jupyter cells complete, people think that the model completes and then they get an error in the 'ls' step. Update the text to make it more obvious that the model needs to complete before they will be able to see the files.

**Comment by wwieder** [comment]
I'm moving this to the tutorial repo
